# Generated by Django 2.1.4 on 2018-12-10 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashondelivery', '0002_auto_20160818_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashondeliverytransaction',
            name='cash_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='txns', to=settings.AUTH_USER_MODEL, verbose_name='Cash Collector'),
        ),
        migrations.AddField(
            model_name='cashondeliverytransaction',
            name='txn_note',
            field=models.TextField(blank=True, null=True, verbose_name='Transaction Note'),
        ),
    ]
